[build]
  # Directory to change to before starting a build
  base = "front/"
  
  # Directory containing the built frontend files
  publish = "dist/"
  
  # Build command for Netlify
  command = "npm run build:netlify"

# Redirects for single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Optional: Environment variables (you can also set these in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"