[build]
  # Directory to change to before starting a build
  base = "backend/"
  
  # Directory containing the built frontend files
  publish = ""
  
  # Build command for Netlify
  command = "./start-background.sh "

# Redirects for single-page application


# Optional: Headers for security


# Optional: Environment variables (you can also set these in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"