// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrralnvbkgokgcgkrhvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhycmFsbnZia2dva2djZ2tyaHZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzk0NjksImV4cCI6MjA2NzY1NTQ2OX0.9rKe0bOglsQZuvIsg8nRwqItFf91n7TgubuCcghu11o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});